name: Knip
on:
  pull_request:

# This permissions config is only required if you are
# not providing own permissive token
permissions:
  checks: write
  issues: write
  pull-requests: write

jobs:
  knip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.1.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install npm packages
        run: npm ci
      - name: Post the knip results
        uses: codex-/knip-reporter@v2.5.0
