name: Knip
on:
  pull_request:

# This permissions config is only required if you are
# not providing own permissive token
permissions:
  checks: write
  issues: write
  pull-requests: write

jobs:
  knip:
    runs-on: ubuntu-latest
    steps:
      - name: Post the knip results
        uses: codex-/knip-reporter@v2.5.0
